---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-app
  namespace: default
  labels:
    app: ecom-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecom-app
  template:
    metadata:
      labels:
        app: ecom-app
    spec:
      containers:
      - name: ecom-app
        image: hafssa260/ecom-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-app
  namespace: default
spec:
  selector:
    app: ecom-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
